force-app/main/default/objects/Account/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color of the Account</description>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/External_Account_Link__c.field-meta.xml
<CustomField>
    <fullName>External_Account_Link__c</fullName>
    <description>External account link ID</description>
    <externalId>true</externalId>
    <label>External Account Link</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountLink__c/AccountLink__c.object-meta.xml
<CustomObject>
    <description>Links to Account</description>
    <label>AccountLink</label>
    <nameField>
        <label>AccountLink Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountLink</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountLink__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountLink</relationshipLabel>
    <relationshipName>AccountLink</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountLink__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <description>Color of Account</description>
    <label>Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountLinkMatched__e/AccountLinkMatched__e.object-meta.xml
<CustomObject>
    <description>Published when an Account is Linked with an AccountLink</description>
    <label>AccountLinkMatched</label>
    <pluralLabel>AccountLinkMatched</pluralLabel>
</CustomObject>

force-app/main/default/objects/AccountLinkMatched__e/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <description>Matched Account Id</description>
    <label>Account Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountLinkMatched__e/fields/Account_Link_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Link_Id__c</fullName>
    <description>Account Link Id</description>
    <label>Account Link Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <description>A custom object for Logging</description>
    <label>Logger</label>
    <nameField>
        <displayFormat>LOG#-{0000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountLinkServiceTest.cls
@isTest
private with sharing class AccountLinkServiceTest {
    private static String successRequestBody = '{"items": [{"color": "red", "externalId": "test123", "accoundId":"001" }, {"color": "blue", "externalId": "123test", "accoundId":"002"}, {"color": "green", "externalId": "testing123","accoundId":"003"}]}';
    private static String noExternalIdBody = '{"items": [{"color": "red", "accoundId":"001" }, {"color": "blue", "accoundId":"002"}, {"color": "green", "externalId": "testing123","accoundId":"003"}]}';
    private static String path = '/api/v1/accountLink';

    @TestSetup
    static void makeData() {
        Account account = new Account(Name = 'Test Account', Color__c = 'red', External_Account_Link__c = 'test123');
        insert account;
    }

    @IsTest
    private static void testHandlePostRequestSuccess() {
        RestRequest request = new RestRequest();
        request.requestURI = path;
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(successRequestBody);
        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        AccountLinkRestResource.handlePostRequest();
        Test.stopTest();

        System.Assert.areEqual(Utils.CREATED, response.statusCode, 'Status code should be 201');
        System.Assert.areEqual(3, [SELECT COUNT() FROM AccountLink__c], '3 records should be created');
        System.Assert.areEqual(
            1,
            [SELECT COUNT() FROM AccountLink__c WHERE Account__c != NULL],
            '1 record should have an account'
        );
        System.Assert.areEqual(0, [SELECT COUNT() FROM Logger__c], 'No logs should be created');
    }

    @IsTest
    private static void testHandlePostRequestDuplicateExternalId() {
        RestRequest request = new RestRequest();
        request.requestURI = path;
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf(noExternalIdBody);
        RestContext.request = request;
        RestResponse response = new RestResponse();
        RestContext.response = response;

        Test.startTest();
        AccountLinkRestResource.handlePostRequest();
        Test.stopTest();

        System.Assert.areEqual(Utils.INTERNAL_SERVER_ERROR, response.statusCode, 'Status code should be 500');
        System.Assert.areEqual(0, [SELECT COUNT() FROM AccountLink__c], 'No records should be created');
        System.Assert.areEqual(0, [SELECT COUNT() FROM Logger__c], 'No logs should be created');
    }

    @IsTest
    private static void testFailedEventPublish() {
        AccountLink__c accountLink = new AccountLink__c(Color__c = 'red');

        Test.startTest();
        AccountLinkService.publishAccountLinkCreatedEvent(new List<AccountLink__c>{ accountLink });
        Test.stopTest();

        System.Assert.isTrue([SELECT COUNT() FROM Logger__c] > 0, 'Log should be created');
    }

    @IsTest
    private static void testGenerateResponseBody() {
        List<AccountLinkMatched__e> matchedAccountLinks = new List<AccountLinkMatched__e>();
        AccountLinkMatched__e matchedAccountLink = new AccountLinkMatched__e(
            Account_Link_Id__c = '001',
            Account_Id__c = '002'
        );
        matchedAccountLinks.add(matchedAccountLink);

        Test.startTest();
        String requestBody = AccountLinkService.generateRequestBody(matchedAccountLinks);
        Test.stopTest();

        Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(requestBody);
        System.Assert.isTrue(responseMap.containsKey('items'), 'Response should contain items key');
    }
}