force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <description>A custom object for Logging</description>
    <label>Logger</label>
    <nameField>
        <displayFormat>LOG#-{0000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Details of the Log</description>
    <label>Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Logger__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Trace of Log</description>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Logger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of the log</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Utils.cls
public with sharing class Utils {
    public static final Integer CREATED = 201;
    public static final Integer INTERNAL_SERVER_ERROR = 500;
    public enum LogType {
        ERROR,
        INFO
    }

    public static Logger__c createLog(LogType logType, String message, String stackTrace) {
        Logger__c log = new Logger__c();
        log.Message__c = message;
        log.Type__c = logType.name();
        log.Stack_Trace__c = stackTrace;
        return log;
    }
}